# Generated by Django 2.1.7 on 2019-02-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha',models.DateField()),
                ('Idioma_Presupuesto',models.CharField(max_length=3)),
                ('Idioma_Informe',models.CharField(max_length=3)),
                ('Numero_de_Inmuebles',models.IntegerField()),
                ('Tipo_Inmueble',models.CharField(max_length=15)),
                ('Descripcion',models.TextField()),
                ('Encargado_por',models.CharField(max_length=50)),
                ('Conocido_por',models.CharField(max_length=20)),
                ('Objetivo_Valoracion',models.CharField(max_length=30)),
                ('Tarifa',models.CharField(max_length=30)),
                ('Comision',models.FloatField()),
                ('Importe_presupuesto',models.FloatField()),
                ('Importe_presupuesto_con_IVA',models.FloatField()),
                ('Provision_inicial',models.FloatField()),
                ('Importe_Provision',models.FloatField()),
                ('Provision_hecha',models.FloatField()),
                ('Fecha_cobro',models.DateField(null=True)),
                ('Deadline_informe',models.DateField(null=True)),
                ('Valoracion_retroactiva',models.CharField(max_length=2)),
                ('Fecha_valoracion_retroactiva',models.DateField(null=True)),
                ('Observaciones',models.CharField(max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),

            ],
        ),
    ]
