# Generated by Django 2.2.12 on 2022-11-20 18:02

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Comision',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Comision (%)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Deadline_informe',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Descripcion',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Encargado_por',
            field=models.CharField(default='Cliente', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Fecha_cobro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Fecha_valoracion_retroactiva',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Idioma_Informe',
            field=models.CharField(choices=[('ESP', 'ESP'), ('CAT', 'CAT'), ('OTRO', 'OTRO')], default='ESP', max_length=3),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Idioma_Presupuesto',
            field=models.CharField(choices=[('ESP', 'ESP'), ('CAT', 'CAT'), ('OTRO', 'OTRO')], default='ESP', max_length=3),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Observaciones',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Provision_hecha',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Provision hecha (%)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Provision_inicial',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Provision Inicial (%)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Tipo_Inmueble',
            field=models.CharField(choices=[('NAVE', 'NAVE'), ('LOCAL', 'LOCAL'), ('VIVIENDA', 'VIVIENDA'), ('EDIFICIO', 'EDIFICIO'), ('OFICINA', 'OFICINA'), ('OTRO', 'OTRO')], default='VIVIENDA', max_length=15),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Valoracion_retroactiva',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='contact',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 18, 2, 47, 968791, tzinfo=utc)),
        ),
    ]
